name: Rust CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.8.0
  SQLX_FEATURES: "rustls,postgres"
  APP_USER: app
  APP_USER_PWD: secret
  APP_DB_NAME: newsletter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        override-file: Cargo.toml

    - name: Run tests
      run: cargo test

    - name: Run linter
      run: cargo clippy -- -D warnings

    - name: Run check format code
      run: cargo fmt -- --check
    
    # - name: Security measurements
      # run: cargo audit